### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by tzelonm** [crisward/riot-tag#16]
Hey,
I wonder if you are going to continue with the project.

Thank you.

**Comment by crisward** [comment]
I use riot2 (yes I know!), so this still works ok for me. A newer version has been updated here for riot4 but I'm unsure if it'll work with vscode.

https://github.com/riot/syntax-highlight

I presume that's why you're asking.

**Comment by tzelonm** [comment]
Sadly, it can't work with vscode.
How hard is it to create a riot4 syntax-highlight based on the sublime version?

Off topic question:
How is it like to use riot?. I'm just starting to use it. :)
And how do you feel about riot4?

**Comment by crisward** [comment]
My original syntax highlighter used text-mate syntax which most editors support. I believe the new uses something specific to sublime, you should try googling for a converter, one may exist.

As for the off topic -

I've created some quite complex projects in riot and really like that you can use it with pug templates for really clean tags. Also when I started using it, riot2 went back to IE8, so that was a big help at the time. You can also be really productive in it, new tags take very little time to write.

However the browser landscape is changing and web components (HTML5 custom elements) are now available in 72% of browsers without any polyfills. If I was just starting to learn a new front end technology I'd be tempted to start with something closer to the web standard (eg [lit-element](https://lit-element.polymer-project.org/)), but IE11 isn't going anywhere soon. I've noticed riot4 also doesn't support IE11, so I'm not sure it'd my first choice anymore (which is a shame).

**Comment by tzelonm** [comment]
Thanks for the answers. 
You gave me something to think about. :)
